[project]
name = "readable-reprs"
description = "Make stdlib reprs evaluatable"
readme = "README.md"
license = "MIT"
license-files = [
    "LICENSE.txt",
]
requires-python = ">=3.13"
dynamic = ["version"]

[dependency-groups]
dev = [
    "cyclonedx-bom>=7.2.1",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
]

[build-system]
requires = ["hatchling==1.28.0", "hatch-vcs==0.5.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
sbom-files = ["bom.json"]

[tool.pytest.ini_options]
pythonpath = [
    "src"
]
